### ISSUE TITLE
Disconnected from: Tern Javascript Server

### ISSUE THREAD

**Issue by fjenett** [mortalapeman/LT-TernJS#26]
OS-X 10.10, LT 0.8, TernJS 0.1.10

With any kind of JS project all i get is:

```
Error: spawn /Applications/lighttable-0.8.1-mac/LightTable.app/Contents/Resources/app/plugins/node/node ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:509:16)
    at eval (/Users/fjenett/Library/Application%20Support/LightTable/plugins/TernJS/ternjs_compiled.js:442:16)
    at eval (/Users/fjenett/Library/Application%20Support/LightTable/plugins/TernJS/ternjs_compiled.js:277:36)
    at eval (/Users/fjenett/Library/Application%20Support/LightTable/plugins/TernJS/ternjs_compiled.js:212:14)
    at eval (/Users/fjenett/Library/Application%20Support/LightTable/plugins/TernJS/ternjs_compiled.js:95:18)
    at eval (/Users/fjenett/Library/Application%20Support/LightTable/plugins/TernJS/ternjs_compiled.js:111:18)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

`Error: spawn` and `Error: channel closed` keep repeating over and over again whenever i type anything.

I'm using `nvm` as node version manager. Also i can not find any node inside the .app bundle's plugin folder (where it seems to look for it in the error message above).

Any idea how to further debug this?

**Comment by Meai** [comment]
apparently the node executable is missing, the file '/Applications/lighttable-0.8.1-mac/LightTable.app/Contents/Resources/app/plugins/node/node' just isnt there. 
put node there and see if it works..

**Comment by rundis** [comment]
The node executable changed when Light Table upgraded from node webkit to Electron in v 0.8.0 of Lt.
I believe this commit fixes it : https://github.com/mortalapeman/LT-TernJS/commit/eb60aff5a583d36f49c15ff689ad61eb81e4d598

Someone just needs to make a new release and then make a pr to https://github.com/LightTable/plugin-metadata

**Comment by fjenett** [comment]
Ok, thanks! … fixed it for now with a link to my local node.

**Comment by jmgaguilera** [comment]
I'm getting same error in Ubuntu 16.04.

`Error: spawn /home/jmgaguilera/bin/lighttable-0.8.1-linux/resources/app/plugins/node/node ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:509:16)
    at eval (/home/jmgaguilera/.config/LightTable/plugins/TernJS/ternjs_compiled.js:442:16)
    at eval (/home/jmgaguilera/.config/LightTable/plugins/TernJS/ternjs_compiled.js:277:36)
    at eval (/home/jmgaguilera/.config/LightTable/plugins/TernJS/ternjs_compiled.js:212:14)
    at eval (/home/jmgaguilera/.config/LightTable/plugins/TernJS/ternjs_compiled.js:95:18)
    at eval (/home/jmgaguilera/.config/LightTable/plugins/TernJS/ternjs_compiled.js:111:18)
    at FSReqWrap.oncomplete (fs.js:82:15)`

 I''m working now, changing line 425 in tern_compiled.js to find my node executable, like this:
{return "/../../../../.nvm/versions/node/v6.9.1/bin/node";

**Comment by tareefdev** [comment]
You just need to download node.js from here: https://nodejs.org , extract it to `lighttable-0.8.1-linux/resources/app/plugins/` rename the folder to just `node` and from inside it, move the contents of `bin` folder to its parent, restart Light Table and that it
